[font]
size = 10.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[window.padding]
x = 1
y = 1

[shell]
program = "/usr/local/bin/fish"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#18181A'
foreground = '#E0DEF4'
